# Generated by Django 4.2 on 2024-03-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=128)),
                ("phone_number", models.CharField(max_length=128)),
                ("company_name", models.CharField(max_length=256)),
                ("sponsor_quantity", models.IntegerField()),
                ("spent_quantity", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("yangi", "Yangi"),
                            ("bekor", "Bekor"),
                            ("moderatsiyada", "Moderatsiyada"),
                            ("tasdiqlangan", "Tasdiqlangan"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=128)),
                ("university_name", models.CharField(max_length=128)),
                (
                    "study_type",
                    models.CharField(
                        choices=[("bakalavr", "Bakalavr"), ("magistr", "Magistr")],
                        max_length=16,
                    ),
                ),
                ("paid_quantity", models.IntegerField(default=0)),
                ("contract_quantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_quantity", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="sponsors.sponsor",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="sponsors.student",
                    ),
                ),
            ],
        ),
    ]
